version: "3.6"
services:

  server:
    image: unit:1.34.2-python3.12
    container_name: unit
    hostname: unit
    labels:
      container_group: unit
    logging:
      driver: journald
      options:
        labels: container_group
    networks:
    - local
    ports:
    - 80:80
    - 9080:9080
    restart: unless-stopped
    volumes:
    - ./config.json:/docker-entrypoint.d/config.json
    - ${DEVSTACK_DIR:?err}/unit/www:/www
