version: "3.6"
services:

  server:
    build: image/.
    image: 172.16.16.1:5000/unit:latest
    container_name: unit
    hostname: unit
    labels:
      container_group: unit
    logging:
      driver: journald
      options:
        labels: container_group
    networks:
    - local
    ports:
    - 80:80
    - 9080:9080
    restart: unless-stopped
    volumes:
    - ./index.html:/www/static/index.html
    - ./requirements.txt:/www/requirements.txt
    - ${DEVSTACK_DIR:?err}/unit/config:/docker-entrypoint.d
    - ${DEVSTACK_DIR:?err}/unit/node_modules:/usr/lib/node_modules
    - ${DEVSTACK_DIR:?err}/www:/www
